


set(PYBLASTER_VERSION_MAJOR 0)
set(PYBLASTER_VERSION_MINOR 2)
set(PYBLASTER_VERSION_BUILD 7)
set(PYBLASTER_VERSION_FULL "${PYBLASTER_VERSION_MAJOR}.${PYBLASTER_VERSION_MINOR}.${PYBLASTER_VERSION_BUILD}")
